### ISSUE TITLE
re: Quick start with Docker compose

### ISSUE THREAD

**Issue by CNSKnight** [Pronovix/walkhub-service#27]
Thanks for the effort guys. Getting a walkhub service up and running quickly is important for users and adoption as well. That said, 

- Running walkhub in production w/out SSL is a non-starter
- We understand docker the only route to serving SSL
- Not everybody (me) has current bandwidth to work out a secure production 'up' quickly

### Two Things
1. Please expand on "DO NOT use this in production". Assuming customized ENV and AUTH values in place, what's wrong with it? (all assuming single-server env)
2. Possibly the sample docker-compose.yml with a layered-on production.yml could be helpful

thanks.

**Comment by tamasd** [comment]
The "DO NOT USE this in production" warning is mostly because the secrets are empty. If you don't have unique secrets then a malicious 3rd party can forge session data. However, if you fill those, and you set the path to your SSL cert/key (we use a docker volume to make them available inside the container) or enable letsencrypt, then I don't see why it wouldn't work in production. In the first couple of months, we ran WalkHub like this.

One caveat with the HTTPS setup: if you make WalkHub HTTPS-only, then it won't work on HTTP sites. If you don't enable HTTPS, then WalkHub will only work on HTTP sites. To make it work on both HTTPS and HTTP, you have to configure it to work on both (ssl or letsencrypt  and the `httpaddr` + `httporigin` settings).
